import postgres from 'postgres';
import * as dotenv from 'dotenv';
import { ALL_SYSTEM_PERMISSIONS } from '../lib/permissions';
import { loadStore } from '../lib/serverStore';

dotenv.config();
dotenv.config({ path: '.env.local' });

const connectionString =
  process.env.DATABASE_URL ||
  process.env.SUPABASE_DB_URL ||
  process.env.POSTGRES_URL;

async function runDatabaseMigrationsAndRoles() {
  if (!connectionString) {
    console.error('❌ Error: DATABASE_URL, SUPABASE_DB_URL, or POSTGRES_URL is not set.');
    console.error('Please configure your database connection string in .env or .env.local');
    process.exit(1);
  }

  console.log('🚀 Connecting to Supabase Postgres database...');

  const sql = postgres(connectionString, {
    max: 1,
    prepare: false, // Essential for Supabase transaction pooler (port 6543)
    ssl: { rejectUnauthorized: false },
  });

  try {
    console.log('📦 Step 1: Creating Postgres Extensions & ENUM types...');
    await sql.unsafe(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);
    await sql.unsafe(`CREATE EXTENSION IF NOT EXISTS "pgcrypto";`);

    // 1. Enums (Strictly 3 roles: SUPER_ADMIN, ADMIN, MEMBER)
    await sql.unsafe(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role_scope') THEN
          CREATE TYPE role_scope AS ENUM('GLOBAL', 'VILLAGE');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'system_role') THEN
          CREATE TYPE system_role AS ENUM('SUPER_ADMIN', 'ADMIN', 'MEMBER');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'member_status') THEN
          CREATE TYPE member_status AS ENUM('active', 'pending', 'suspended');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'member_role') THEN
          CREATE TYPE member_role AS ENUM('MEMBER', 'ADMIN');
        END IF;
      END $$;
    `);

    console.log('📦 Step 2: Dropping existing tables to ensure clean Auto-Increment identity IDs...');
    await sql.unsafe(`
      DROP TABLE IF EXISTS audit_logs CASCADE;
      DROP TABLE IF EXISTS messages CASCADE;
      DROP TABLE IF EXISTS group_messages CASCADE;
      DROP TABLE IF EXISTS public_infos CASCADE;
      DROP TABLE IF EXISTS announcements CASCADE;
      DROP TABLE IF EXISTS elders CASCADE;
      DROP TABLE IF EXISTS gallery CASCADE;
      DROP TABLE IF EXISTS events CASCADE;
      DROP TABLE IF EXISTS social_works CASCADE;
      DROP TABLE IF EXISTS complaints CASCADE;
      DROP TABLE IF EXISTS members CASCADE;
      DROP TABLE IF EXISTS user_village_roles CASCADE;
      DROP TABLE IF EXISTS user_permissions CASCADE;
      DROP TABLE IF EXISTS permissions CASCADE;
      DROP TABLE IF EXISTS villages CASCADE;
      DROP TABLE IF EXISTS gram_panchayats CASCADE;
      DROP TABLE IF EXISTS districts CASCADE;
      DROP TABLE IF EXISTS states CASCADE;
    `);

    console.log('📦 Step 3: Creating Multi-Tenancy & Geography Tables with AUTO-INCREMENT IDs...');
    // 2. States
    await sql.unsafe(`
      CREATE TABLE states (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        name_hindi text NOT NULL,
        code text NOT NULL UNIQUE,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_states_code ON states (code);`);

    // 3. Districts
    await sql.unsafe(`
      CREATE TABLE districts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        state_id BIGINT NOT NULL REFERENCES states(id) ON DELETE RESTRICT,
        name text NOT NULL,
        name_hindi text NOT NULL,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_districts_state_id ON districts (state_id);`);

    // 4. Gram Panchayats
    await sql.unsafe(`
      CREATE TABLE gram_panchayats (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        district_id BIGINT NOT NULL REFERENCES districts(id) ON DELETE RESTRICT,
        name text NOT NULL,
        name_hindi text NOT NULL,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_gram_panchayats_district_id ON gram_panchayats (district_id);`);

    // 5. Villages
    await sql.unsafe(`
      CREATE TABLE villages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug text NOT NULL UNIQUE,
        name text NOT NULL,
        name_hindi text NOT NULL,
        gram_panchayat_id BIGINT REFERENCES gram_panchayats(id) ON DELETE SET NULL,
        district_id BIGINT REFERENCES districts(id) ON DELETE SET NULL,
        state_id BIGINT REFERENCES states(id) ON DELETE SET NULL,
        org_name text NOT NULL DEFAULT 'Gramodaya Youth Manch',
        org_name_hindi text NOT NULL DEFAULT 'ग्रामोदय यूथ मंच',
        slogan_hindi text DEFAULT 'युवा शक्ति • ग्राम विकास • उज्ज्वल भविष्य',
        tagline_hindi text DEFAULT 'युवा शक्ति से ग्रामोदय की ओर',
        org_purpose_hindi text,
        contact_mobile text,
        contact_email text,
        banner_photo_url text,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_villages_slug ON villages (slug);`);
    await sql.unsafe(`CREATE INDEX idx_villages_panchayat_id ON villages (gram_panchayat_id);`);
    await sql.unsafe(`CREATE INDEX idx_villages_district_id ON villages (district_id);`);

    console.log('📦 Step 4: Creating RBAC & Permissions Tables with AUTO-INCREMENT IDs...');
    // 6. Permissions Catalog
    await sql.unsafe(`
      CREATE TABLE permissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code text NOT NULL UNIQUE,
        name text NOT NULL,
        module text NOT NULL,
        description text,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `);

    // 7. User Permissions (PBAC Overrides)
    await sql.unsafe(`
      CREATE TABLE user_permissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        permission_code text NOT NULL REFERENCES permissions(code) ON DELETE CASCADE,
        scope_type role_scope NOT NULL DEFAULT 'VILLAGE',
        scope_id BIGINT,
        is_granted boolean NOT NULL DEFAULT TRUE,
        granted_by text,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_user_permissions_user_id ON user_permissions (user_id);`);
    await sql.unsafe(`CREATE INDEX idx_user_permissions_perm_code ON user_permissions (permission_code);`);

    // 8. User Village Roles
    await sql.unsafe(`
      CREATE TABLE user_village_roles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        village_id BIGINT NOT NULL REFERENCES villages(id) ON DELETE CASCADE,
        role system_role NOT NULL DEFAULT 'MEMBER',
        is_primary boolean NOT NULL DEFAULT FALSE,
        assigned_by text,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_user_village_roles_user_id ON user_village_roles (user_id);`);
    await sql.unsafe(`CREATE INDEX idx_user_village_roles_village_id ON user_village_roles (village_id);`);

    console.log('📦 Step 5: Creating Core Application Feature Tables with AUTO-INCREMENT IDs...');
    // 9. Members
    await sql.unsafe(`
      CREATE TABLE members (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        name text NOT NULL,
        mobile text NOT NULL UNIQUE,
        email text,
        password_hash text,
        status member_status NOT NULL DEFAULT 'active',
        role member_role NOT NULL DEFAULT 'MEMBER',
        system_role system_role NOT NULL DEFAULT 'MEMBER',
        photo_url text,
        organization_name text DEFAULT 'ग्रामोदय यूथ मंच',
        father_name text,
        dob text,
        gender text,
        address text DEFAULT 'ग्राम रसूलपुर, ग्राम पंचायत बहेरा',
        occupation text,
        designation text,
        political_background text,
        blood_group text,
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_members_mobile ON members (mobile);`);
    await sql.unsafe(`CREATE INDEX idx_members_status ON members (status);`);
    await sql.unsafe(`CREATE INDEX idx_members_system_role ON members (system_role);`);
    await sql.unsafe(`CREATE INDEX idx_members_village_id ON members (village_id);`);

    // 10. Complaints
    await sql.unsafe(`
      CREATE TABLE complaints (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        user_id UUID,
        title text NOT NULL,
        category text NOT NULL DEFAULT 'Other',
        description text NOT NULL,
        location text DEFAULT 'Rasoolpur',
        reporter_name text NOT NULL,
        reporter_mobile text NOT NULL,
        status text NOT NULL DEFAULT 'NEW',
        photo_url text,
        video_url text,
        is_demo boolean DEFAULT FALSE,
        resolved_at timestamptz,
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_complaints_village_id ON complaints (village_id);`);
    await sql.unsafe(`CREATE INDEX idx_complaints_status ON complaints (status);`);

    // 11. Social Works
    await sql.unsafe(`
      CREATE TABLE social_works (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        title text NOT NULL,
        description text NOT NULL,
        date date DEFAULT current_date NOT NULL,
        location text DEFAULT 'Rasoolpur',
        submitter_name text NOT NULL,
        submitter_mobile text NOT NULL,
        photo_url text,
        video_url text,
        status text NOT NULL DEFAULT 'pending',
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_social_works_village_id ON social_works (village_id);`);

    // 12. Events
    await sql.unsafe(`
      CREATE TABLE events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        title text NOT NULL,
        description text,
        date text NOT NULL,
        time text DEFAULT '10:00 AM' NOT NULL,
        location text DEFAULT 'Rasoolpur Village',
        photo_url text,
        video_url text,
        status text NOT NULL DEFAULT 'PUBLISHED',
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_events_village_id ON events (village_id);`);

    // 13. Gallery
    await sql.unsafe(`
      CREATE TABLE gallery (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        caption text,
        photo_url text NOT NULL,
        uploaded_by text DEFAULT 'Admin' NOT NULL,
        uploaded_by_mobile text,
        date date DEFAULT current_date NOT NULL,
        status text NOT NULL DEFAULT 'published',
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_gallery_village_id ON gallery (village_id);`);

    // 14. Elders Honor
    await sql.unsafe(`
      CREATE TABLE elders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        name text NOT NULL,
        age text NOT NULL,
        role text,
        contribution text,
        photo_url text,
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_elders_village_id ON elders (village_id);`);

    // 15. Announcements
    await sql.unsafe(`
      CREATE TABLE announcements (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        title text NOT NULL,
        content text NOT NULL,
        date date DEFAULT current_date NOT NULL,
        published_by text DEFAULT 'ग्रामोदय यूथ मंच' NOT NULL,
        is_urgent boolean DEFAULT FALSE,
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);
    await sql.unsafe(`CREATE INDEX idx_announcements_village_id ON announcements (village_id);`);

    // 16. Public Infos
    await sql.unsafe(`
      CREATE TABLE public_infos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        title text NOT NULL,
        description text NOT NULL,
        category text NOT NULL,
        submitter_name text NOT NULL,
        submitter_mobile text NOT NULL,
        status text NOT NULL DEFAULT 'pending',
        created_at timestamptz DEFAULT now() NOT NULL,
        updated_at timestamptz DEFAULT now() NOT NULL
      );
    `);

    // 17. Live Chat & Direct Messages
    await sql.unsafe(`
      CREATE TABLE group_messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        sender_name text NOT NULL,
        sender_role text DEFAULT 'Member',
        sender_mobile text,
        sender_photo text,
        text text NOT NULL,
        timestamp text NOT NULL,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `);

    await sql.unsafe(`
      CREATE TABLE messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        room_id text DEFAULT 'general',
        sender_id text NOT NULL,
        sender_name text NOT NULL,
        sender_role text DEFAULT 'Member',
        sender_mobile text,
        sender_photo text,
        text text NOT NULL,
        photo_url text,
        timestamp text NOT NULL,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `);

    // 18. Audit Logs
    await sql.unsafe(`
      CREATE TABLE audit_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        village_id BIGINT REFERENCES villages(id) ON DELETE SET NULL,
        user_id text,
        user_name text NOT NULL,
        action text NOT NULL,
        details text,
        ip_address text,
        timestamp timestamptz DEFAULT now() NOT NULL
      );
    `);

    console.log('✅ All 18 database tables created with AUTO-INCREMENT identity IDs!');

    console.log('🌱 Step 6: Seeding Multi-Tenancy Hierarchy, Roles and Community Data...');
    const store = loadStore();

    // 1. Seed State: Uttar Pradesh (ID 1)
    const [stateRow] = await sql`
      INSERT INTO states (name, name_hindi, code)
      VALUES ('Uttar Pradesh', 'उत्तर प्रदेश', 'UP')
      ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name
      RETURNING id;
    `;
    const stateId = stateRow?.id || 1;

    // 2. Seed District: Jaunpur (ID 1)
    const [distRow] = await sql`
      INSERT INTO districts (state_id, name, name_hindi)
      VALUES (${stateId}, 'Jaunpur', 'जौनपुर')
      RETURNING id;
    `;
    const districtId = distRow?.id || 1;

    // 3. Seed Gram Panchayat: Bahera (ID 1)
    const [gpRow] = await sql`
      INSERT INTO gram_panchayats (district_id, name, name_hindi)
      VALUES (${districtId}, 'Bahera', 'बहेरा')
      RETURNING id;
    `;
    const gramPanchayatId = gpRow?.id || 1;

    // 4. Seed Primary Village: Rasoolpur (ID 1)
    const [vilRow] = await sql`
      INSERT INTO villages (
        slug, name, name_hindi, gram_panchayat_id, district_id, state_id,
        org_name, org_name_hindi, slogan_hindi, tagline_hindi, org_purpose_hindi, is_active
      )
      VALUES (
        'rasoolpur', 'Rasoolpur', 'रसूलपुर', ${gramPanchayatId}, ${districtId}, ${stateId},
        'Gramodaya Youth Manch', 'ग्रामोदय यूथ मंच', 'युवा शक्ति • ग्राम विकास • उज्ज्वल भविष्य',
        'युवा शक्ति से ग्रामोदय की ओर',
        'ग्रामोदय यूथ मंच गांव के युवाओं, परिवारों और बुजुर्गों को एक साथ जोड़कर ग्राम विकास, शिक्षा, रोजगार, स्वच्छता, पर्यावरण, सामाजिक जागरूकता और जरूरतमंद लोगों की सहायता के लिए कार्य करने का एक सामुदायिक मंच है।',
        TRUE
      )
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        name_hindi = EXCLUDED.name_hindi,
        org_name = EXCLUDED.org_name,
        org_name_hindi = EXCLUDED.org_name_hindi
      RETURNING id;
    `;
    const villageId = vilRow?.id || 1;

    // 5. Seed System Permissions Catalog (Auto-increment IDs)
    console.log(`Inserting ${ALL_SYSTEM_PERMISSIONS.length} system permissions...`);
    for (const perm of ALL_SYSTEM_PERMISSIONS) {
      await sql`
        INSERT INTO permissions (code, name, module, description)
        VALUES (${perm.code}, ${perm.name}, ${perm.module}, ${perm.description})
        ON CONFLICT (code) DO UPDATE SET
          name = EXCLUDED.name,
          module = EXCLUDED.module,
          description = EXCLUDED.description;
      `;
    }

    // 6. Seed Admins & 3 Canonical Roles (SUPER_ADMIN, ADMIN)
    console.log(`Inserting ${store.admins.length} leadership admins & assigning roles...`);
    for (const admin of store.admins) {
      const sysRole = admin.isHead ? 'SUPER_ADMIN' : 'ADMIN';
      const [insertedMember] = await sql`
        INSERT INTO members (
          village_id, name, mobile, role, system_role, status, photo_url, organization_name, address
        )
        VALUES (
          ${villageId}, ${admin.name}, ${admin.mobile}, 'ADMIN', ${sysRole}::system_role, 'active',
          ${admin.photoUrl || null}, 'ग्रामोदय यूथ मंच', ${`${admin.village || 'Rasoolpur'}, ग्राम पंचायत ${admin.gramPanchayat || 'Bahera'}`}
        )
        ON CONFLICT (mobile) DO UPDATE SET
          name = EXCLUDED.name,
          photo_url = EXCLUDED.photo_url,
          system_role = EXCLUDED.system_role
        RETURNING id;
      `;

      const memberId = insertedMember?.id;
      if (memberId) {
        // Assign user_village_role
        await sql`
          INSERT INTO user_village_roles (user_id, village_id, role, is_primary, assigned_by)
          VALUES (
            ${memberId}, ${villageId}, ${sysRole}::system_role, TRUE, 'system_init'
          );
        `;
      }
    }

    // 7. Seed Members with auto-increment ID and role 'MEMBER'
    console.log(`Inserting ${store.members.length} members...`);
    for (const member of store.members) {
      await sql`
        INSERT INTO members (
          village_id, name, mobile, role, system_role, status, photo_url, organization_name, address
        )
        VALUES (
          ${villageId}, ${member.name}, ${member.mobile}, 'MEMBER', 'MEMBER'::system_role,
          ${member.status || 'active'}::member_status, ${member.photoUrl || null},
          ${member.organizationName || 'ग्रामोदय यूथ मंच'}, ${member.address || 'ग्राम रसूलपुर, ग्राम पंचायत बहेरा'}
        )
        ON CONFLICT (mobile) DO NOTHING;
      `;
    }

    // 8. Seed Announcements
    console.log(`Inserting ${store.announcements.length} announcements...`);
    for (const ann of store.announcements) {
      await sql`
        INSERT INTO announcements (village_id, title, content, published_by, is_urgent)
        VALUES (${villageId}, ${ann.title}, ${ann.content}, ${ann.publishedBy || 'ग्रामोदय यूथ मंच'}, ${(ann as any).isUrgent || false});
      `;
    }

    console.log('🎉 ✅ All tables migrated with Auto-Increment IDs and roles successfully!');
  } catch (error) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  } finally {
    await sql.end();
  }
}

runDatabaseMigrationsAndRoles();
