-- Migration: 20260814000004_create_rbac_and_multivillage.sql
-- Optimized RBAC Architecture for Gramodaya Youth Manch with Auto-Increment IDs

-- 1. Create Villages Table
CREATE TABLE IF NOT EXISTS public.villages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    name_hindi TEXT NOT NULL,
    gram_panchayat_name TEXT DEFAULT 'Bahera',
    gram_panchayat_name_hindi TEXT DEFAULT 'बहेरा',
    district_name TEXT DEFAULT 'Jaunpur',
    district_name_hindi TEXT DEFAULT 'जौनपुर',
    state_name TEXT DEFAULT 'Uttar Pradesh',
    state_name_hindi TEXT DEFAULT 'उत्तर प्रदेश',
    org_name TEXT NOT NULL DEFAULT 'Gramodaya Youth Manch',
    org_name_hindi TEXT NOT NULL DEFAULT 'ग्रामोदय यूथ मंच',
    slogan_hindi TEXT DEFAULT 'युवा शक्ति • ग्राम विकास • उज्ज्वल भविष्य',
    tagline_hindi TEXT DEFAULT 'युवा शक्ति से ग्रामोदय की ओर',
    org_purpose_hindi TEXT,
    contact_mobile TEXT,
    contact_email TEXT,
    banner_photo_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create Village Admins Table
CREATE TABLE IF NOT EXISTS public.village_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    village_id BIGINT NOT NULL REFERENCES public.villages(id) ON DELETE CASCADE,
    assigned_by_mobile TEXT,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_member_village UNIQUE (member_id, village_id)
);

-- 3. Add columns to members if not present and enforce 3-role CHECK constraint
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'village_id') THEN
        ALTER TABLE public.members ADD COLUMN village_id BIGINT REFERENCES public.villages(id) ON DELETE RESTRICT DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'role') THEN
        ALTER TABLE public.members ADD COLUMN role TEXT NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'MEMBER'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'complaints' AND column_name = 'village_id') THEN
        ALTER TABLE public.complaints ADD COLUMN village_id BIGINT REFERENCES public.villages(id) ON DELETE CASCADE DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'social_works' AND column_name = 'village_id') THEN
        ALTER TABLE public.social_works ADD COLUMN village_id BIGINT REFERENCES public.villages(id) ON DELETE CASCADE DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'public_infos' AND column_name = 'village_id') THEN
        ALTER TABLE public.public_infos ADD COLUMN village_id BIGINT REFERENCES public.villages(id) ON DELETE CASCADE DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'events' AND column_name = 'village_id') THEN
        ALTER TABLE public.events ADD COLUMN village_id BIGINT REFERENCES public.villages(id) ON DELETE CASCADE DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'announcements' AND column_name = 'village_id') THEN
        ALTER TABLE public.announcements ADD COLUMN village_id BIGINT REFERENCES public.villages(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'gallery' AND column_name = 'village_id') THEN
        ALTER TABLE public.gallery ADD COLUMN village_id BIGINT REFERENCES public.villages(id) ON DELETE CASCADE DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'elders' AND column_name = 'village_id') THEN
        ALTER TABLE public.elders ADD COLUMN village_id BIGINT REFERENCES public.villages(id) ON DELETE CASCADE DEFAULT 1;
    END IF;
END $$;

-- 4. Seed Default Village (Rasoolpur: ID 1)
INSERT INTO public.villages (id, slug, name, name_hindi, gram_panchayat_name, district_name, is_active)
VALUES (1, 'rasoolpur', 'Rasoolpur', 'रसूलपुर', 'Bahera', 'Hardoi', TRUE)
ON CONFLICT (id) DO NOTHING;

