-- Migration: 20260815000001_add_gram_panchayats_and_address_structure.sql
-- Description: Add Gram Panchayats master table and structured address fields to members & villages

-- 1. Create Gram Panchayats Table if not exists
CREATE TABLE IF NOT EXISTS public.gram_panchayats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_hindi TEXT,
    district_id BIGINT REFERENCES public.districts(id) ON DELETE SET NULL,
    district_name TEXT NOT NULL DEFAULT 'Jaunpur',
    district_name_hindi TEXT DEFAULT 'जौनपुर',
    state_id BIGINT REFERENCES public.states(id) ON DELETE SET NULL,
    state_name TEXT NOT NULL DEFAULT 'Uttar Pradesh',
    state_name_hindi TEXT DEFAULT 'उत्तर प्रदेश',
    block_name TEXT DEFAULT 'Shahganj',
    block_name_hindi TEXT DEFAULT 'शाहगंज',
    pincode TEXT DEFAULT '222139',
    post_office TEXT DEFAULT 'Rasulpur',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gram_panchayats_name ON public.gram_panchayats (name);
CREATE INDEX IF NOT EXISTS idx_gram_panchayats_district ON public.gram_panchayats (district_name);
CREATE INDEX IF NOT EXISTS idx_gram_panchayats_pincode ON public.gram_panchayats (pincode);

-- 2. Add Structured Address Columns to Members Table
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'pincode') THEN
        ALTER TABLE public.members ADD COLUMN pincode TEXT DEFAULT '222139';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'state') THEN
        ALTER TABLE public.members ADD COLUMN state TEXT DEFAULT 'Uttar Pradesh';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'district') THEN
        ALTER TABLE public.members ADD COLUMN district TEXT DEFAULT 'Jaunpur';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'block') THEN
        ALTER TABLE public.members ADD COLUMN block TEXT DEFAULT 'Shahganj';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'gram_panchayat') THEN
        ALTER TABLE public.members ADD COLUMN gram_panchayat TEXT DEFAULT 'Bahera';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'village_name') THEN
        ALTER TABLE public.members ADD COLUMN village_name TEXT DEFAULT 'Rasoolpur';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'post_office') THEN
        ALTER TABLE public.members ADD COLUMN post_office TEXT DEFAULT 'Rasulpur';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'house_no') THEN
        ALTER TABLE public.members ADD COLUMN house_no TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'street') THEN
        ALTER TABLE public.members ADD COLUMN street TEXT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_members_pincode ON public.members (pincode);
CREATE INDEX IF NOT EXISTS idx_members_gram_panchayat ON public.members (gram_panchayat);
CREATE INDEX IF NOT EXISTS idx_members_district ON public.members (district);

-- 3. Add Location & Postal Columns to Villages Table
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'villages' AND column_name = 'pincode') THEN
        ALTER TABLE public.villages ADD COLUMN pincode TEXT DEFAULT '222139';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'villages' AND column_name = 'block_name') THEN
        ALTER TABLE public.villages ADD COLUMN block_name TEXT DEFAULT 'Shahganj';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'villages' AND column_name = 'block_name_hindi') THEN
        ALTER TABLE public.villages ADD COLUMN block_name_hindi TEXT DEFAULT 'शाहगंज';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'villages' AND column_name = 'post_office') THEN
        ALTER TABLE public.villages ADD COLUMN post_office TEXT DEFAULT 'Rasulpur';
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_villages_pincode ON public.villages (pincode);

-- 4. Seed Initial Gram Panchayats
INSERT INTO public.gram_panchayats (name, name_hindi, district_name, district_name_hindi, state_name, block_name, pincode, post_office, is_active)
VALUES 
    ('Bahera', 'बहेरा', 'Hardoi', 'हरदोई', 'Uttar Pradesh', 'Hardoi', '241125', 'Bahera Rasoolpur', TRUE),
    ('Jamua', 'जमुआ', 'Jaunpur', 'जौनपुर', 'Uttar Pradesh', 'Badlapur', '222125', 'Jamua', TRUE),
    ('Khetasarai', 'खेतासराय', 'Jaunpur', 'जौनपुर', 'Uttar Pradesh', 'Shahganj', '222139', 'Khetasarai', TRUE),
    ('Badlapur', 'बदलापुर', 'Jaunpur', 'जौनपुर', 'Uttar Pradesh', 'Badlapur', '222125', 'Badlapur', TRUE),
    ('Shahganj', 'शाहगंज', 'Jaunpur', 'जौनपुर', 'Uttar Pradesh', 'Shahganj', '222139', 'Shahganj', TRUE)
ON CONFLICT DO NOTHING;

