-- Migration: 20260814000000_create_base_tables.sql
-- Description: Create all primary database tables with auto-incrementing IDs

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Members Table (सदस्य)
CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supabase_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'pending', 'suspended')),
    photo_url TEXT,
    organization_name TEXT DEFAULT 'ग्रामोदय यूथ मंच',
    father_name TEXT,
    dob TEXT,
    address TEXT DEFAULT 'ग्राम रसूलपुर, ग्राम पंचायत बहेरा',
    role TEXT NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'MEMBER')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_members_mobile ON public.members (mobile);
CREATE INDEX IF NOT EXISTS idx_members_status ON public.members (status);
CREATE INDEX IF NOT EXISTS idx_members_role ON public.members (role);

-- 3. Complaints Table (ग्राम समस्याएं)
CREATE TABLE IF NOT EXISTS public.complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Other',
    description TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT 'Rasoolpur',
    reporter_name TEXT NOT NULL,
    reporter_mobile TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'NEW' CHECK (status IN ('NEW', 'ACTION IN PROGRESS', 'RESOLVED')),
    photo_url TEXT,
    video_url TEXT,
    is_demo BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_complaints_status ON public.complaints (status);
CREATE INDEX IF NOT EXISTS idx_complaints_category ON public.complaints (category);
CREATE INDEX IF NOT EXISTS idx_complaints_reporter_mobile ON public.complaints (reporter_mobile);

-- 4. Social Works Table (सामाजिक कार्य)
CREATE TABLE IF NOT EXISTS public.social_works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    location TEXT NOT NULL DEFAULT 'Rasoolpur',
    submitter_name TEXT NOT NULL,
    submitter_mobile TEXT NOT NULL,
    photo_url TEXT,
    video_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'published')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_social_works_submitter ON public.social_works (submitter_mobile);
CREATE INDEX IF NOT EXISTS idx_social_works_status ON public.social_works (status);

-- 5. Events Table (ग्राम कार्यक्रम)
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    date TEXT NOT NULL,
    time TEXT NOT NULL DEFAULT '10:00 AM',
    location TEXT NOT NULL DEFAULT 'Rasoolpur Village',
    photo_url TEXT,
    video_url TEXT,
    status TEXT NOT NULL DEFAULT 'PUBLISHED' CHECK (status IN ('DRAFT', 'PENDING', 'PUBLISHED', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_status ON public.events (status);

-- 6. Gallery Table (गैलरी)
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caption TEXT,
    photo_url TEXT NOT NULL,
    uploaded_by TEXT NOT NULL DEFAULT 'Admin',
    uploaded_by_mobile TEXT,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('pending', 'published')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Elders Honor Table (बुजुर्ग सम्मान)
CREATE TABLE IF NOT EXISTS public.elders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mobile TEXT,
    location TEXT DEFAULT 'Rasoolpur',
    details TEXT,
    photo_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. Announcements Table (सूचना पट्ट)
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    published_by TEXT NOT NULL DEFAULT 'ग्रामोदय यूथ मंच',
    published_by_mobile TEXT,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. Public Information Table (सार्वजनिक सूचना)
CREATE TABLE IF NOT EXISTS public.public_infos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    information TEXT NOT NULL,
    photo_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_public_infos_mobile ON public.public_infos (mobile);

-- 10. Real-time Group Chat Messages
CREATE TABLE IF NOT EXISTS public.group_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_name TEXT NOT NULL,
    sender_mobile TEXT,
    sender_photo TEXT,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. 1-on-1 Direct Messages
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_mobile TEXT NOT NULL,
    sender_name TEXT NOT NULL,
    recipient_mobile TEXT NOT NULL,
    recipient_name TEXT NOT NULL,
    text TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_pair ON public.messages (sender_mobile, recipient_mobile);

-- 12. Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    admin_name TEXT NOT NULL DEFAULT 'Admin',
    admin_mobile TEXT DEFAULT '',
    record_affected TEXT DEFAULT '',
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON public.audit_logs (timestamp DESC);
